services:
  mysql:
    container_name: multi-module-microservices-db
    image: mysql:5.7
    volumes:
      # - multi-module-microservices:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password

  customer:
    container_name: customer-service
    depends_on:
      - mysql
    build: /customer
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql

  fraud:
    container_name: fraud-service
    depends_on:
      - mysql
    build: /fraud
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysql

# volumes:
#   multi-module-microservices:
