# Spring Profiles & SpringBoot External config
# https://www.baeldung.com/spring-profiles
# https://www.baeldung.com/properties-with-spring
# https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.profile-specific
# https://stackoverflow.com/questions/60565706/how-to-load-the-spring-profiles-active-value-in-the-client-service-dynamically
# https://stackoverflow.com/questions/25855795/spring-boot-and-multiple-external-configuration-files#:~:text=To%20add%20different%20files%20you,or%20file%20location%20(directories).&text=The%20one%20above%20will%20add,will%20be%20consulted%20for%20application.

# Eureka-server docker environment endpoint
# https://github.com/spring-cloud/spring-cloud-netflix/issues/2442

services:
  mysql:
    container_name: multi-module-microservices-db
    image: mysql:5.7
    volumes:
      # - multi-module-microservices:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password

  eureka-server:
    container_name: eureka-server
    build: /eureka-server
    ports:
      - "8761:8761"
    restart: on-failure

  customer:
    container_name: customer-service
    depends_on:
      - mysql
      - eureka-server
    build: /customer
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      SPRING_PROFILES_ACTIVE: docker
      # Different syntax
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url=jdbc:mysql": "//jdbc:mysql:3306/spring_microservices_customer",
        "spring.datasource.username": "root",
        "spring.datasource.password": "password",
        "spring.jpa.hibernate.ddl-auto": "update"
        }'

  fraud:
    container_name: fraud-service
    depends_on:
      - mysql
      - eureka-server
    build: /fraud
    ports:
      - 8081:8081
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url=jdbc:mysql": "//jdbc:mysql:3306/spring_microservices_fraud",
        "spring.datasource.username": "root",
        "spring.datasource.password": "password",
        "spring.jpa.hibernate.ddl-auto": "update",
        "eureka.client.service-url.defaultZone": "http://eureka-server:8761/eureka"
        }'

# volumes:
#   multi-module-microservices:
