services:
  mysql:
    container_name: multi-module-microservices-db
    image: mysql:5.7
    volumes:
      - multi-module-microservices:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring_microservices

  customer:
    container_name: customer-service
    depends_on:
      - mysql
    build: /customer
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql

volumes:
  multi-module-microservices:
