# https://stackoverflow.com/a/73508528/16648127

services:
  mysql:
    container_name: multi-module-microservices-db
    image: mysql:5.7
    volumes:
      # - multi-module-microservices:/var/lib/mysql # volum
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
  
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    # environment:
    #   - STORAGE_TYPE=mysql
    #   # Point the zipkin at the storage backend
    #   - MYSQL_HOST=mysql
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    container_name: eureka
    depends_on:
      - zipkin
    build: /eureka-server
    ports:
      - "8761:8761"
    restart: on-failure
    environment:
      spring.zipkin.baseurl: http://zipkin:9411

  customer:
    container_name: customer
    depends_on:
      - mysql
      - eureka-server
      - zipkin
    build: /customer
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      SPRING_PROFILES_ACTIVE: docker
      # Different syntax
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url=jdbc:mysql": "//jdbc:mysql:3306/spring_microservices_customer",
        "spring.datasource.username": "root",
        "spring.datasource.password": "password",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.zipkin.baseurl": "http://zipkin:9411"
        }'

  fraud:
    container_name: fraud
    depends_on:
      - mysql
      - eureka-server
      - zipkin
    build: /fraud
    ports:
      - 8081:8081
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url=jdbc:mysql": "//jdbc:mysql:3306/spring_microservices_fraud",
        "spring.datasource.username": "root",
        "spring.datasource.password": "password",
        "spring.jpa.hibernate.ddl-auto": "update",
        "eureka.client.service-url.defaultZone": "http://eureka-server:8761/eureka",
        "spring.zipkin.baseurl": "http://zipkin:9411"
        }'
        
# volumes:
#   multi-module-microservices:
